const $=id=>document.getElementById(id);const _=object=>object.value="";const e=object=>object.style.border="2px solid #AA0000";const c=object=>object.style.border="none";const d=object=>object.style.display!="none";const viewLoader=()=>$("loader-container").style.display="flex";const hideLoader=()=>$("loader-container").style.display="none";$("host-ranking-screen").style.display="none";function updateHeight(){if(window.innerWidth<=780){["left-container","right-container"].forEach(className=>{for(let container of document.getElementsByClassName(className)){container.style.height=`${$("main").offsetHeight}px`;}});}}
function updateLineNumbers(object){let lineCount=object.value.split("\n").length;let temp="";for(let i=1;i<=lineCount;i++){temp+=`${i}\n`;}
object.parentNode.children[0].innerText=temp;}
function updateScroll(object){object.parentNode.children[0].scrollTop=object.scrollTop;}
function updateCode(object,event){let start=object.selectionStart;let end=object.selectionEnd;let beforeStart=object.value.substring(0,start);let startEnd=object.value.substring(start,end);let afterEnd=object.value.substring(end);if(event.keyCode==9&&event.shiftKey){event.preventDefault();if(object.value.substring(beforeStart.lastIndexOf("\n")+1,beforeStart.lastIndexOf("\n")+2)=="\t"){object.value=object.value.substring(0,beforeStart.lastIndexOf("\n")+1)+object.value.substring(beforeStart.lastIndexOf("\n")+2);if(object.value.substring(start-1,start)=="\n"){object.selectionStart=start;}else{object.selectionStart=start-1;}
object.selectionEnd=end-1;start=object.selectionStart;end=object.selectionEnd;beforeStart=object.value.substring(0,start);startEnd=object.value.substring(start,end);afterEnd=object.value.substring(end);}
object.value=beforeStart+startEnd.replace(/\n\t/g,"\n")+afterEnd;object.selectionStart=start;object.selectionEnd=end-startEnd.split("\n\t").length+1;}else if(event.keyCode==9){event.preventDefault();object.value=beforeStart+'\t'+startEnd.replace(/\n/g,"\n\t")+afterEnd;object.selectionStart=start+1;object.selectionEnd=end+startEnd.split("\n").length;}else if(event.keyCode==13){event.preventDefault();let count=((beforeStart.split("{").length-1)-(beforeStart.split("}").length-1))+((beforeStart.split("[").length-1)-(beforeStart.split("]").length-1))+((beforeStart.split("(").length-1)-(beforeStart.split(")").length-1));let temp=object.value.substring(start-1,end+1);if(temp=="{}"||temp=="[]"||temp=="()"){object.value=beforeStart+'\n'+'\t'.repeat(count)+'\n'+'\t'.repeat(count-1)+afterEnd;}else{object.value=beforeStart+'\n'+'\t'.repeat(count)+afterEnd;}
object.selectionEnd=start+1+count;updateLineNumbers(object);}}
let pages=["home","host-matches","about","contact"];let pageViewed="home";let switchingPages=false;let switchingElements=false;function switchPage(object){let temp=pages.indexOf(object.dataset.page)-pages.indexOf(pageViewed);if(temp!=0&&!switchingPages){switchingPages=true;let newPage=$(object.dataset.page);let oldPage=$(pageViewed);newPage.style.display="block";if(temp>0){newPage.style.top="-100%";oldPage.style.animation="leftOut 0.5s forwards";newPage.style.animation="rightIn 0.5s forwards";}else if(temp<0){oldPage.style.top="-100%";oldPage.style.animation="rightOut 0.5s forwards";newPage.style.animation="leftIn 0.5s forwards";}
setTimeout(()=>{oldPage.style.display="none";newPage.style.top="0%";switchingPages=false;},500);pageViewed=object.dataset.page;}}
function switchElement(oldElement,newElement){if(!switchingElements){switchingElements=true;oldElement.style.animation="fadeOut 0.25s forwards";setTimeout(()=>{newElement.style.animation="fadeIn 0.25s forwards";oldElement.style.display="none";newElement.style.display="block";},250);setTimeout(()=>switchingElements=false,500);}}
function post(data){return fetch("https://jhihyangwu.pythonanywhere.com",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:JSON.stringify(data)}).then(res=>res.json())}
function submitMessage(){let data={"action":"submitMessage"};["name","email","message"].forEach(element=>data[element]=$(`contact-form-${element}`).value);viewLoader();post(data).then(()=>{["name","email","message"].forEach(element=>_($(`contact-form-${element}`)));hideLoader();}).catch(()=>hideLoader());return false;}
let signInUsername=$("sign-in-form-username");let signInPassword=$("sign-in-form-password");let signUpUsername=$("sign-up-form-username");let signUpPassword=$("sign-up-form-password");let signUpConfirmPassword=$("sign-up-form-confirm-password");function cNotAuth(){setTimeout(()=>{[signInUsername,signInPassword,signUpUsername,signUpPassword,signUpConfirmPassword].forEach(object=>{c(object);_(object);});},250);}
function viewSignIn(){switchElement($("sign-up-form"),$("sign-in-form"));cNotAuth();}
function viewSignUp(){switchElement($("sign-in-form"),$("sign-up-form"));cNotAuth();}
function signIn(){c(signInUsername);c(signInPassword);let data={"action":"signIn","username":signInUsername.value,"password":signInPassword.value};viewLoader();post(data).then(response=>{if(response["valid"]){viewIsAuth(data["username"],response["tables"]);setTimeout(()=>{_(signInUsername);_(signInPassword);},250);}else{_(signInUsername);_(signInPassword);e(signInUsername);e(signInPassword);}
hideLoader();}).catch(()=>hideLoader());return false;}
function signUp(){c(signUpUsername);c(signUpPassword);c(signUpConfirmPassword);if(signUpPassword.value==signUpConfirmPassword.value){let data={"action":"signUp","username":signUpUsername.value,"password":signUpPassword.value};viewLoader();post(data).then(response=>{if(response["valid"]){viewIsAuth(data["username"],response["tables"]);setTimeout(()=>{_(signUpUsername);_(signUpPassword);_(signUpConfirmPassword);},250);}else{if(response["username"]){_(signUpUsername);e(signUpUsername);}
if(response["password"]){_(signUpPassword);_(signUpConfirmPassword);e(signUpPassword);e(signUpConfirmPassword);}}
hideLoader();}).catch(()=>hideLoader());}else{_(signUpConfirmPassword);e(signUpConfirmPassword);}
return false;}
function viewIsAuth(username,data){$("username").innerText=username;updateTables(data);switchElement($("not-auth"),$("is-auth"));}
post({"action":"checkAuth"}).then(response=>{if(response["valid"]){viewIsAuth(response["username"],response["tables"]);}});function updateTables(data){$("find-problems").children[1].innerHTML="";$("my-problems").children[1].innerHTML="";$("match-history").children[1].innerHTML="";data["findProblems"].forEach(problem=>$("find-problems").children[1].innerHTML+=`<tr><td>${problem[0]}</td><td>${problem[1]}</td><td>${new Date(problem[2]).toLocaleString().replace(",","")}</td><td>${problem[3]}</td><td><span class="clickable"onclick="viewTableDropdown(this)"data-date="${problem[2]}">…</span></td></tr>`);data["myProblems"].forEach(problem=>$("my-problems").children[1].innerHTML+=`<tr><td>${problem[0]}</td><td>${new Date(problem[1]).toLocaleString().replace(",","")}</td><td>${problem[2]}</td><td>${problem[3]}</td><td><span class="clickable"onclick="viewTableDropdown(this)"data-date="${problem[1]}">…</span></td></tr>`);data["matchHistory"].forEach(match=>$("match-history").children[1].innerHTML+=`<tr><td>${match[0]}</td><td>${new Date(match[1]).toLocaleString().replace(",","")}</td><td><span class="clickable"onclick="viewTableDropdown(this)"data-date="${match[1]}">…</span></td></tr>`);}
let hostFileData={};let guestFileData={};let hostFileViewed;let guestFileViewed;const saveHostFile=key=>hostFileViewed&&(hostFileData[key]=$("host-code-area").value);const saveGuestFile=key=>guestFileViewed&&(guestFileData[key]=$("code-area").value);function viewFile(object){object.parentNode.childNodes.forEach(element=>element.style.color="#888888");object.style.color="#444444";if(object.parentNode.id=="host-files"){saveHostFile(hostFileViewed);hostFileViewed=object.id;$("host-code-area").value=hostFileData[hostFileViewed];updateLineNumbers($("host-code-area"));}else{saveGuestFile(guestFileViewed);guestFileViewed=object.innerText;$("code-area").value=guestFileData[guestFileViewed];updateLineNumbers($("code-area"));}}
let hostFileIndex=0;function addFile(){$("new-problem-files").children[0].insertAdjacentHTML("beforeend",`<tr><td><input type="text"placeholder="FILE NAME"oninput="updateHostFileLabel(this)"data-index="${hostFileIndex}"></td><td onclick="removeFile(this)"class="clickable"data-index="${hostFileIndex}">−</td></tr>`);$("host-files").innerHTML+=`<span id="host-file-label-${hostFileIndex}"onclick="viewFile(this)"></span>`;hostFileData[`host-file-label-${hostFileIndex}`]="package Code;\nimport Code.*;\n\n";viewFile($("host-files").lastChild);hostFileIndex++;}
const updateHostFileLabel=object=>$(`host-file-label-${object.dataset.index}`).innerText=object.value;function removeFile(object){$(`host-file-label-${object.dataset.index}`).remove();object.parentNode.remove();if($("host-files").firstChild){viewFile($("host-files").firstChild);}else{_($("host-code-area"));hostFileViewed=undefined;updateLineNumbers($("host-code-area"));}
delete hostFileData[`host-file-label-${object.dataset.index}`];}
function addTestCase(){$("new-problem-test-cases").children[0].insertAdjacentHTML("beforeend",`<tr><td><input type="text"placeholder="FUNCTION CALL"><input type="text"placeholder="EXPECTED OUTPUT"></td><td onclick="removeTestCase(this)"class="clickable">−</td></tr>`);}
const removeTestCase=object=>object.parentNode.remove();function submitProblem(edit,date=""){saveHostFile(hostFileViewed);let data={"action":"submitProblem","problemName":$("new-problem-form-problem-name").value,"description":$("new-problem-form-description").value,"files":{},"testCases":[],"public":$("new-problem-form-public").checked,"edit":edit,"date":date};for(const key in hostFileData){data["files"][$(key).innerText]=hostFileData[key];}
let temp=$("new-problem-test-cases").children[0];for(let i=1;i<temp.children.length;i++){data["testCases"].push([temp.children[i].children[0].children[0].value,temp.children[i].children[0].children[1].value]);}
viewLoader();post(data).then(response=>{updateTables(response["tables"]);let temp=$("explorer-bar").children[0];temp.value="MY PROBLEMS";switchTable(temp);switchingElements=false;switchElement($("host-coding-screen"),$("explorer"));hideLoader();}).catch(()=>hideLoader());}
function resetNewProblem(){_($("new-problem-form-problem-name"));_($("new-problem-form-description"));let temp=$("new-problem-files").children[0];for(let i=temp.children.length-1;i>=1;i--){temp.children[i].remove();}
$("host-files").innerHTML="";hostFileData={};hostFileViewed=undefined;temp=$("new-problem-test-cases").children[0];for(let i=temp.children.length-1;i>=1;i--){temp.children[i].remove();}
$("new-problem-form-public").checked=true;addFile();addTestCase();}
let tableViewed="find-problems";function switchTable(object){$("table-drop-down").style.display="none";tableDropdown=0;let temp={"FIND PROBLEMS":"find-problems","MY PROBLEMS":"my-problems","MATCH HISTORY":"match-history"}[object.value];switchElement($(tableViewed),$(temp));setTimeout(()=>{$(temp).style.display="table";},250);tableViewed=temp;}
function viewNewProblem(){resetNewProblem();$("submit-new-problem").onclick=()=>submitProblem(false);switchElement($("explorer"),$("host-coding-screen"));setTimeout(()=>{$("host-coding-screen").style.display="flex";updateHeight();},250);}
function viewSettings(){$("settings").style.animation="fadeIn 0.25s forwards";$("settings").style.display="flex";}
let tableDropdown=0;window.onclick=event=>{if(event.target==$("settings")){$("settings").style.animation="fadeOut 0.25s forwards";setTimeout(()=>{$("settings").style.display="none";let password=$("reset-password-form-password");let confirmPassword=$("reset-password-form-confirm-password");c(password);c(confirmPassword);},250);}
if(event.target!=$("table-drop-down")){if(tableDropdown==2){$("table-drop-down").style.display="none";tableDropdown=0;}else if(tableDropdown==1){tableDropdown++;}}}
function resetPassword(){let password=$("reset-password-form-password");let confirmPassword=$("reset-password-form-confirm-password");c(password);c(confirmPassword);if(password.value==confirmPassword.value){let data={"action":"resetPassword","password":password.value}
viewLoader();post(data).then(response=>{if(response["valid"]){$("settings").click();setTimeout(()=>{_(password);_(confirmPassword);},250);}else{_(password);_(confirmPassword);e(password);e(confirmPassword);}
hideLoader();}).catch(()=>hideLoader());}else{_(confirmPassword);e(confirmPassword);}
return false;}
function signOut(){viewLoader();viewSignIn();post({"action":"signOut"}).then(()=>{$("settings").click();switchingElements=false;switchElement($("is-auth"),$("not-auth"));setTimeout(()=>{$("not-auth").style.display="flex";let temp=$("explorer-bar").children[0];temp.value="FIND PROBLEMS";switchingElements=false;switchTable(temp);},250);hideLoader();}).catch(()=>hideLoader());}
let previousTableDropdown;function viewTableDropdown(object){if(tableDropdown==0||object!=previousTableDropdown){let temp=$("table-drop-down");let isAuthor=(tableViewed=="find-problems")&&(object.parentNode.parentNode.children[1].innerText==$("username").innerText);temp.innerHTML="";if(tableViewed=="find-problems"||tableViewed=="my-problems"){temp.innerHTML+=`<div onclick="hostProblem('${object.dataset.date}')">HOST</div>`;}
if(tableViewed=="my-problems"||isAuthor){temp.innerHTML+=`<div onclick="viewProblem(true, '${object.dataset.date}')">EDIT</div>`;}else{if(tableViewed=="match-history"){temp.innerHTML+=`<div onclick="viewMatchHistory('${object.dataset.date}')">VIEW</div>`;}else{temp.innerHTML+=`<div onclick="viewProblem(false, '${object.dataset.date}')">VIEW</div>`;}}
if(tableViewed!="find-problems"||isAuthor){temp.innerHTML+=`<div onclick="deleteObject('${object.dataset.date}')">DELETE</div>`;}
temp=object.getBoundingClientRect();$("table-drop-down").style.top=`${temp.bottom+5}px`;$("table-drop-down").style.right=`calc(100%-${temp.right}px)`;$("table-drop-down").style.display="inline-block";tableDropdown=1;previousTableDropdown=object;}}
function hostProblem(date){let data={"action":"hostProblem","date":date}
viewLoader();post(data).then(response=>{$("match-id").innerText=response["matchID"];switchElement($("explorer"),$("host-waiting-screen"));updateLastResponse(true,response["matchID"]);hideLoader();}).catch(()=>hideLoader());}
function joinMatch(){let name=$("join-form-your-name");let matchID=$("join-form-match-id");c(name);c(matchID);let data={"action":"joinMatch","matchID":matchID.value,"name":name.value}
viewLoader();post(data).then(response=>{if(response["valid"]){switchElement($("not-join"),$("is-join"));updateLastResponse(false,matchID.value,name.value);}else{if(!response["name"]){_(name);e(name);}
if(!response["matchID"]){_(matchID);e(matchID);}}
hideLoader();}).catch(()=>hideLoader());return false;}
let resetData;let retry=0;function updateLastResponse(host,matchID,name=null){let data={"action":"updateLastResponse","host":host,"matchID":matchID,"name":name}
post(data).then(response=>{retry=0;if(!host&&response["problemName"]){switchingElements=false;resetData=JSON.parse(JSON.stringify(response["files"]));guestFileData=response["files"];$("problem").innerHTML=`<div>${response["problemName"]}</div>${response["description"]}`;Object.keys(guestFileData).forEach(fileName=>$("files").innerHTML+=`<span onclick="viewFile(this)">${fileName}</span>`);viewFile($("files").firstChild);response["testCases"].forEach(testCase=>$("test-cases").children[0].innerHTML+=`<tr><td>${testCase[0]}</td><td>${testCase[1]}</td><td></td><td></td></tr>`);switchElement($("waiting-screen"),$("coding-screen"));setTimeout(()=>{$("coding-screen").style.display="flex";updateHeight();},250);viewTestCases();}
if(host){if(d($("host-waiting-screen"))){$("name-container").innerHTML="";response["guestNames"].forEach(name=>$("name-container").innerHTML+=`<div onclick="kickGuest('${matchID}', '${name}')">${name}</div>`);$("people-count").innerText=`PEOPLE:${response["guestNames"].length}`;$("completed-count").innerText=`COMPLETED:0/${response["guestNames"].length}`;}else if(d($("host-ranking-screen"))){[[$("time-tbody"),response["time"]],[$("attempts-tbody"),response["attempts"]],[$("runtime-tbody"),response["runtime"]]].forEach(temp=>{temp[0].innerHTML="";for(let i=0;i<Object.keys(temp[1]).length;i++){temp[0].innerHTML+=`<tr><td>${i+1}</td><td>${Object.keys(temp[1])[i]}</td><td>${temp[1][Object.keys(temp[1])[i]]}</td></tr>`;}});$("completed-count").innerText=`COMPLETED:${Object.keys(response["time"]).length}/${response["guestNames"].length}`;}}else{if(response["status"]=="ended"){leaveMatch();}
if(response["time"]){$("time-rank").innerText=response["time"];$("attempts-rank").innerText=response["attempts"];$("runtime-rank").innerText=response["runtime"];}}
if((host&&(d($("host-waiting-screen"))||d($("host-ranking-screen"))))||(!host&&d($("is-join")))){updateLastResponse(host,matchID,name);}}).catch(()=>{if(retry<4){retry++;setTimeout(()=>updateLastResponse(host,matchID,name),2500);}else{if(host){switchingElements=false;if(d($("host-waiting-screen"))){switchElement($("host-waiting-screen"),$("explorer"));}else{switchElement($("host-ranking-screen"),$("explorer"));}
setTimeout(()=>{$("name-container").innerHTML="";$("people-count").innerText="PEOPLE: 0";$("time-tbody").innerHTML="";$("attempts-tbody").innerHTML="";$("runtime-tbody").innerHTML="";},250);}else{leaveMatch();}}});}
function startMatch(){let data={"action":"startMatch","matchID":$("match-id").innerText}
viewLoader();post(data).then(()=>{switchElement($("host-waiting-screen"),$("host-ranking-screen"));setTimeout(()=>$("host-ranking-screen").style.display="flex",250);hideLoader();}).catch(()=>hideLoader());}
function endMatch(){let data={"action":"endMatch","matchID":$("match-id").innerText}
viewLoader();post(data).then(response=>{updateTables(response["tables"]);switchingElements=false;if(d($("host-waiting-screen"))){switchElement($("host-waiting-screen"),$("explorer"));}else{switchElement($("host-ranking-screen"),$("explorer"));let temp=$("explorer-bar").children[0];temp.value="MATCH HISTORY";switchingElements=false;switchTable(temp);}
setTimeout(()=>{$("name-container").innerHTML="";$("people-count").innerText="PEOPLE: 0";$("time-tbody").innerHTML="";$("attempts-tbody").innerHTML="";$("runtime-tbody").innerHTML="";},250);hideLoader();}).catch(()=>hideLoader());}
function viewTestCases(){$("console").style.display="none";$("test-cases").style.display="table";$("console-button").style.color="#888888";$("test-cases-button").style.color="#444444";}
function viewConsole(){$("test-cases").style.display="none";$("console").style.display="block";$("test-cases-button").style.color="#888888";$("console-button").style.color="#444444";}
function run(){saveGuestFile(guestFileViewed);let data={"action":"run","matchID":$("join-form-match-id").value,"name":$("join-form-your-name").value,"files":guestFileData}
viewLoader();post(data).then(response=>{$("console").innerText=response["console"];for(let i=0;i<response["functionOutput"].length;i++){let temp=$("test-cases").children[0].children[i];temp.children[2].innerText=response["functionOutput"][i];temp.children[3].innerHTML=response["correctCases"][i];}
if(response["status"]==-1){viewConsole();}else if(response["status"]==0){viewTestCases();}else{$("time").innerText=response["stats"][0];$("attempts").innerText=response["stats"][1];$("runtime").innerText=response["stats"][2];$("time-rank").innerText=response["time"];$("attempts-rank").innerText=response["attempts"];$("runtime-rank").innerText=response["runtime"];switchElement($("coding-screen"),$("ranking-screen"));setTimeout(()=>$("ranking-screen").style.display="flex",250);}
hideLoader();}).catch(()=>hideLoader());}
function reset(){$("code-area").value=resetData[guestFileViewed];updateLineNumbers($("code-area"));}
function leaveMatch(){switchingElements=false;switchElement($("is-join"),$("not-join"));setTimeout(()=>{$("waiting-screen").style.display="flex";$("coding-screen").style.display="none";$("ranking-screen").style.display="none";$("waiting-screen").style.animation="";$("test-cases").children[0].innerHTML="";$("console").innerText="";$("files").innerHTML="";$("line-numbers").innerHTML="";$("code-area").value="";guestFileData={};guestFileViewed=undefined;$("join-form-match-id").value="";},250);}
let matchHistoryFiles;let matchHistoryFileOrder;function viewMatchHistory(date){let data={"action":"viewMatchHistory","date":date}
viewLoader();post(data).then(response=>{$("new-problem-form").style.display="none";$("scoreboard").style.display="table";$("cancel-new-problem").style.display="none";$("submit-new-problem").style.display="none";$("back-to-explorer").style.display="inline-block";$("host-files").innerHTML="";$("host-line-numbers").innerHTML="";$("host-code-area").value="";$("scoreboard").children[1].innerHTML="";response["scoreboard"].forEach(row=>$("scoreboard").children[1].innerHTML+=`<tr onclick="viewMatchHistoryFiles('${row[0]}')"><td>${row[0]}</td><td>${row[1]}</td><td>${row[2]}</td><td>${row[3]}</td></tr>`);matchHistoryFiles=response["files"];matchHistoryFileOrder=response["fileOrder"];switchElement($("explorer"),$("host-coding-screen"));setTimeout(()=>{$("host-coding-screen").style.display="flex";updateHeight();},250);hideLoader();}).catch(()=>hideLoader());}
function backToExplorer(){switchElement($("host-coding-screen"),$("explorer"));setTimeout(()=>{$("scoreboard").style.display="none";$("new-problem-form").style.display="block";$("back-to-explorer").style.display="none";$("cancel-new-problem").style.display="inline-block";$("submit-new-problem").style.display="inline-block";},250);}
function viewMatchHistoryFiles(name){$("host-files").innerHTML="";$("host-line-numbers").innerHTML="";$("host-code-area").value="";if(Object.keys(matchHistoryFiles[name]).length!=0){matchHistoryFileOrder.forEach(fileName=>$("host-files").innerHTML+=`<span onclick="viewMatchHistoryFile(this, '${name}', '${fileName}')">${fileName}</span>`);}
if($("host-files").firstChild){$("host-files").firstChild.click();}}
function viewMatchHistoryFile(object,name,file){object.parentNode.childNodes.forEach(element=>element.style.color="#888888");object.style.color="#444444";$("host-code-area").value=matchHistoryFiles[name][file];updateLineNumbers($("host-code-area"));}
function deleteObject(date){let data={"action":"deleteObject","problem":$("explorer-bar").children[0].value!="MATCH HISTORY","date":date}
viewLoader();post(data).then(response=>{updateTables(response["tables"]);hideLoader();}).catch(()=>hideLoader());}
function viewProblem(edit,date){if(!edit){$("cancel-new-problem").style.display="none";$("submit-new-problem").style.display="none";$("back-to-explorer").style.display="inline-block";}else{$("submit-new-problem").onclick=()=>submitProblem(true,date);}
let data={"action":"viewProblem","date":date}
viewLoader();post(data).then(response=>{$("new-problem-form-problem-name").value=response["problemName"];$("new-problem-form-description").value=response["description"];let temp=$("new-problem-files").children[0];for(let i=temp.children.length-1;i>=1;i--){temp.children[i].remove();}
$("host-files").innerHTML="";$("host-line-numbers").innerHTML="";$("host-code-area").value="";hostFileData={};hostFileViewed=undefined;temp=$("new-problem-test-cases").children[0];for(let i=temp.children.length-1;i>=1;i--){temp.children[i].remove();}
Object.keys(response["files"]).forEach(fileName=>{addFile();let temp=$("new-problem-files").children[0].lastChild.children[0].children[0];temp.value=fileName;updateHostFileLabel(temp);$("host-code-area").value=response["files"][fileName];});if($("host-files").firstChild){viewFile($("host-files").firstChild);}
response["testCases"].forEach(testCase=>{addTestCase();let temp=$("new-problem-test-cases").children[0].lastChild.children[0];temp.children[0].value=testCase[0];temp.children[1].value=testCase[1];});$("new-problem-form-public").checked=response["public"];switchElement($("explorer"),$("host-coding-screen"));setTimeout(()=>{$("host-coding-screen").style.display="flex";updateHeight();},250);hideLoader();}).catch(()=>hideLoader());}
function filterTables(object){[$("find-problems").children[1],$("my-problems").children[1],$("match-history").children[1]].forEach(tbody=>{for(let i=0;i<tbody.children.length;i++){if(tbody.children[i].innerText.toUpperCase().indexOf(object.value.toUpperCase())!=-1){tbody.children[i].style.display="";}else{tbody.children[i].style.display="none";}}});}
function kickGuest(matchID,name){let data={"action":"kickGuest","matchID":matchID,"name":name}
viewLoader();post(data).then(()=>hideLoader()).catch(()=>hideLoader());}